# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ossuo', '0035_auto_20160617_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='mBranchAddress',
            field=models.CharField(default='', help_text='Full address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='mBranchAddressLink',
            field=models.URLField(default='', help_text='Link to google maps', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='mBranchAddressSVG',
            field=models.CharField(default='', help_text='Paste SVG code here', max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='mBranchAddressTitle',
            field=models.CharField(default='', help_text='Full address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ContactEmail',
            field=models.CharField(default='', help_text='Email address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ContactTelephone',
            field=models.CharField(default='', help_text='Telephone', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ContactTwitter',
            field=models.CharField(default='', help_text='Twitter', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='EmailNewsletterTeaser',
            field=models.CharField(default='', help_text='Text that sits above the email newsletter', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='sBranchAddress',
            field=models.CharField(default='', help_text='Full address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='sBranchAddressLink',
            field=models.URLField(default='', help_text='Link to google maps', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='sBranchAddressSVG',
            field=models.CharField(default='', help_text='Paste SVG code here', max_length=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='sBranchAddressTitle',
            field=models.CharField(default='', help_text='Full address', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='HeadQrAddressTitle',
            field=models.CharField(help_text='Full address', max_length=255),
        ),
    ]
